openapi: 3.0.0
info:
  title: Test List API
  version: 1.0.0
servers:
  - url: http://localhost:8888
paths:
  /items:
    get:
      summary: Get items
      responses:
        '200':
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        status:
          type: string
